name: "Deploy"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    
jobs:
  # Remove the previous builds if there is a new one running
  redundancy-check:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  deploy:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          healthcheck: "https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/"
          rollbackonhealthcheckfailed: true